### ISSUE TITLE
Unknown: no check for this service -> please add a debug function

### ISSUE THREAD

**Issue by linuxmail** [veepee-oss/check_consul#1]
Hi,

thanks for the plugin. I tried to get it working under Debian Stretch, but the only message I got back was:

`Unknown: no check for this service`

It would be great, if there would be any "debug" mode, so that I can see, what goes wrong. 
I took a TCPDump, I saw : HTTP/1.1 500 Internal Server Error. So problem was, that the DC was written in UPPERCASE, instead of lowercase.

Thank you very much.

**Comment by damoun** [comment]
Hi @linuxmail,

You're right, We should add more debug/info on problem in this plugin.
Currently, I use the python module `consulate` to request the API, I will try to find a way to expose more info from the API call on failure.
